#!/bin/bash

echo $1 > status
# Commit status with trailing space if nothing has changed.
if [[ $(git status 2> /dev/null | tail -n1) = "nothing to commit (working directory clean)" ]]; then
  echo "$1 " > status
fi
git commit -am "Exit status is $1"
git push origin master

